#!/bin/bash

./wait.sh postgres 5432
PGPASSWORD=postgres \
psql -h postgres -U postgres -c "CREATE DATABASE scalarest"

echo "Running mode $MODE"

# If you want to optimize the memory usage...
#export SBT_OPTS="-Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=1024M -Xss2M"

if [ "$MODE" = "production" ]; then
    PROPERTIES="-Dlogback.configurationFile=src/main/resources/logback-prod.xml"
else
    PROPERTIES="-Dlogback.configurationFile=src/main/resources/logback.xml"
fi

./sbt $PROPERTIES run